<a href="https://colab.research.google.com/github/ErrrMAK/5bukv/blob/master/Pandas_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from scipy import  stats
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
plt.style.use('ggplot')
%matplotlib inline

In [3]:
n_st = 70
m_st = 25

n_lan = 38
m_lan = 7

n_gr = 41
m_gr = 12

n_nw = 105
m_nw = 41

alpha = 0.05


In [4]:
m_st/n_st, m_lan/n_lan, m_gr/n_gr, m_nw/n_nw

(0.35714285714285715,
 0.18421052631578946,
 0.2926829268292683,
 0.3904761904761905)

In [5]:
from statsmodels.stats.proportion import proportions_ztest

_, p1 = proportions_ztest((m_st, m_lan),
                          (n_st, n_lan),
                          value=0,
                          alternative='larger')
_, p2 = proportions_ztest((m_st, m_gr), (n_st, n_gr), value=0, alternative='larger')
_, p3 = proportions_ztest((m_st, m_nw), (n_st, n_nw), value=0, alternative='larger')

pval = np.array([p1,p2,p3])
pval

array([0.03008672, 0.24343199, 0.67209806])

Метод Бонферрони

In [6]:
pval > 0.05/3

array([ True,  True,  True])

In [7]:
from statsmodels.sandbox.stats.multicomp import multipletests

rejected, p_corrected, _, _ = multipletests(pval,
                                            alpha = 0.05,
                                            method = 'bonferroni')
p_corrected

array([0.09026015, 0.73029598, 1.        ])

In [ ]:
p_corrected > 0.05

Метод Холма

In [8]:
from statsmodels.sandbox.stats.multicomp import multipletests

rejected, p_corrected, _, _ = multipletests(pval,
                                            alpha = 0.05,
                                            method = 'holm')
p_corrected

array([0.09026015, 0.48686399, 0.67209806])

In [9]:
p_corrected > 0.05

array([ True,  True,  True])